### ISSUE TITLE
virt manager kvm/qemu setup

### ISSUE THREAD

**Issue by bitcubix** [bitcubix/arch#11]
setup script for fully working virt manager environment

- [ ] kvm setup https://wiki.archlinux.org/title/KVM
- [ ] qemu install https://wiki.archlinux.org/title/QEMU
- [ ] libvirt, bridge utils and all other needed tools auto install and config
- [ ] virt-manager installation and configuration
- [ ] good documentation

**Comment by Raj-Pansuriya** [comment]
I might be able to write a script for this. Allow me to contribute!
